### ISSUE TITLE
The application doesn't respond

### ISSUE THREAD

**Issue by coco7nut001** [Rdimo/DiscordRAT#16]
![image](https://user-images.githubusercontent.com/76842080/156694976-a07500b7-f403-4dd5-b0c0-cbef88b74dba.png)
Idk why but I have a valid bot token and guild id, everything works just fine and the program is still running.

Pls help

**Comment by Omexy** [comment]
Hey coco,

We can't really get much information on what has occurred here for your bot to not work as intended. Could you please upload a ZIP file of everything in the directory where the bot is located? That way, the helpers or someone else can investigate your issue and identify what you have done wrong in order to solve your issue.
Hope this will help! :)

- **Omexy**

**Comment by coco7nut001** [comment]
> Hey coco,
> 
> We can't really get much information on what has occurred here for your bot to not work as intended. Could you please upload a ZIP file of everything in the directory where the bot is located? That way, the helpers or someone else can investigate your issue and identify what you have done wrong in order to solve your issue. Hope this will help! :)
> 
> * **Omexy**

Oh nvm I kind of figured out myself
